[AndroidTV] ダイアログ→ガイドへの変更
スマホ→AndroidTV向けに変更
AlertDialogで以下のエラーがでる
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

エラーは↓の理由
https://developer.android.com/training/tv/start/layouts?hl=ja#leanback-theme